#Requires -Version 5.1
<#
.SYNOPSIS
    HCStudio v5.0 - FIX51 Phuong an B: dong goi 1 file HCStudio-Setup.exe
    chua TAT CA: app + dll + sea_g2p.bin + 14 file trong so (~607 MB).

.DESCRIPTION
    Copy 1 file duy nhat sang may khong mang -> chay 1 lan -> app + weights
    xep dung cho (weights vao %APPDATA%\HCStudio\models\vieneu-v3-turbo,
    app vao %LOCALAPPDATA%\HCStudio) -> offline vinh vient.

    Yeu cau tren may build (GitHub windows-latest co san):
      - Inno Setup 6 (ISCC.exe)
      - Da chay scripts/fetch-weights-setup.ps1 truoc de co payload weights.

.EXAMPLE
    powershell -File scripts\fetch-weights-setup.ps1
    powershell -File scripts\make-setup.ps1 -DistDir dist
#>
param(
    [string]$DistDir    = "dist",
    [string]$WeightsDir = "build\setup-payload\weights",
    [string]$OutDir     = "build\setup",
    [string]$Version    = "5.0"
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function Die([string]$msg) {
    Write-Host "LOI: $msg" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path (Join-Path $DistDir "HCStudio.exe"))) {
    Die "Khong thay $DistDir\HCStudio.exe - hay build -Full truoc."
}
if (-not (Test-Path $WeightsDir)) {
    Die "Khong thay payload weights: $WeightsDir - hay chay scripts\fetch-weights-setup.ps1 truoc."
}

# - Tim ISCC (Inno Setup 6) ------------------------------------------------
$iscc = $null
foreach ($cand in @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
    "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    "C:\Program Files\Inno Setup 6\ISCC.exe"
)) {
    if ($cand -and (Test-Path $cand)) { $iscc = $cand; break }
}
if (-not $iscc) {
    $cmd = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($cmd) { $iscc = $cmd.Source }
}
if (-not $iscc) {
    Die "Khong tim thay Inno Setup 6 (ISCC.exe). Choco: choco install innosetup -y"
}
Write-Host "ISCC: $iscc"

# - Sinh setup.iss (ASCII thuan) --------------------------------------------
$distAbs   = (Resolve-Path $DistDir).Path
$weightAbs = (Resolve-Path $WeightsDir).Path
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$outAbs = (Resolve-Path $OutDir).Path

$iss = @"
; HCStudio v5.0 - FIX51 single-file setup (auto-generated by make-setup.ps1)
[Setup]
AppName=HCStudio
AppVersion=$Version
AppPublisher=HCStudio
DefaultDirName={localappdata}\HCStudio
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
OutputDir=$outAbs
OutputBaseFilename=HCStudio-Setup
Compression=lzma2/max
SolidCompression=yes
LZMAUseSeparateProcess=yes
WizardStyle=modern
UninstallDisplayIcon={app}\HCStudio.exe
; Weights khong bi xoa khi go cai dat - cai lai khong phai tai lai.

[Files]
; App + runtime DLL (trong dist, keo theo thu muc con neu co)
Source: "$distAbs\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; 14 file trong so -> dung cho models dir cua app (%APPDATA%\HCStudio\models\vieneu-v3-turbo)
Source: "$weightAbs\*"; DestDir: "{userappdata}\HCStudio\models\vieneu-v3-turbo"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\HCStudio"; Filename: "{app}\HCStudio.exe"
Name: "{autodesktop}\HCStudio"; Filename: "{app}\HCStudio.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Tao icon man hinh neu"; Flags: unchecked

[Run]
Filename: "{app}\HCStudio.exe"; Description: "Mo HCStudio ngay"; Flags: postinstall nowait skipifsilent
"@

$issPath = Join-Path $OutDir "setup.iss"
# Ghi ASCII that su (ISCC an toan voi ansi codepage)
[System.IO.File]::WriteAllText($issPath, $iss, [System.Text.Encoding]::ASCII)
Write-Host "Da sinh $issPath"

# - Chay ISCC ----------------------------------------------------------------
& $iscc $issPath
if ($LASTEXITCODE -ne 0) { Die "ISCC that bai (exit $LASTEXITCODE)." }

$exe = Join-Path $OutDir "HCStudio-Setup.exe"
if (-not (Test-Path $exe)) { Die "Khong thay output $exe" }
$mb = [math]::Round((Get-Item $exe).Length / 1MB, 1)
$sha = (Get-FileHash -Path $exe -Algorithm SHA256).Hash.ToLower()
Write-Host ""
Write-Host "THANH CONG: $exe ($mb MB)"
Write-Host "SHA256: $sha"
